config/routes.rb
Rails.application.routes.draw do

 resources :conversations do
    resources :messages
  end
  devise_for :users
  #resource :shops
  #root 'shops#index'
  get "/shops", to: "shops#index", as: "root"
  post "/shops", to: "shops#create"
  get "/shops/new", to: "shops#new", as: "new_shops"
  get "/shops/:id", to: "shops#show", as: "shop"
  put "/shops/:id", to: "shops#update"
  patch "/shops/:id", to: "shops#update"
  delete "/shops/:id", to: "shops#destroy"
  get "/shops/:id/edit", to: "shops#edit", as: "edit_shops"

  # get "/conversations", to: "conversations#index", as: "conversations"
  # post "/conversations", to: "conversations#create"
  # get "/messages", to: "messages#index", as: "messages"
  # post "/messages", to: "messages#create", as: "coversations_messages"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :shops
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # This scope validation takes the sender_id and recipient_id for the conversation and checks whether a conversation exists between the two ids because we only want two users to have one conversation.

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/messages.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :user
	belongs_to :category
	validates :title, :description, :price, :color, presence: true
	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shops
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.all
  end



  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversations_path(@conversation)
  end

  private
    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_conversation

  def index
    @messages = @conversation.messages

    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end

    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end

    @message = @conversation.messages.new
  end

  def create
    
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  def new
    @message = @conversation.messages.new
  end



  private

    def message_params
      params.require(:message).permit(:body, :user_id)
    end

    def find_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_shop, only: [:show, :edit, :update, :destroy]

  def index
    

    @shops = Shop.all

     if params[:category].blank?
  	@shops = Shop.all
    else
      @category_id = Category.find_by(name: params[:category]).id
      @shops = Shop.where(:category_id => @category_id)
   end
  end

  def show
    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: @shop.title,
            description: @shop.description,
            amount: @shop.price * 100,
            currency: 'aud',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                listing_id: @shop.id
            }
        },
        success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@shop.id}",
        cancel_url: "#{root_url}listings"
    )

    @session_id = session.id
   
  	
  end


  def new
  	@shop = current_user.shops.create
     @categories = Category.all.map{ |c| [c.name, c.id]}
  	
  end

  def create

  	@shop = current_user.shops.build(shop_params)
     @shop.category_id = params[:category_id]
  	if @shop.save
  		redirect_to root_path
  	else

  		render 'new'

  	end
  end

    def edit
      @categories = Category.all.map{ |c| [c.name, c.id] }
    end


  	def update
       @shop.category_id = params[:category_id] 
      @shop = Shop.update(params["id"], shop_params)
       if @shop.update(shop_params)
        redirect_to root_path
        else
          render 'edit'
      end
    end

    def destroy
      Shop.find(params[:id]).destroy
      redirect_to root_path
      
    end


  


  private

  def find_shop
  	@shop =Shop.find(params[:id])
  	
  end



  def shop_params

  	params.require(:shop).permit(:title, :description, :price, :category_id, :image, :color, :search)

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/conversations/index.html.erb
<div class="columns">
  <div class="column is-3">
    <h3 class="title is-3">All Users</h3>
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
       <%= link_to "Message #{user.email}", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post" %>
      <% end %>
    <% end %>
  </div>

  <div class="column is-7">
    <h3 class="title is-3">Conversations</h3>
    <% @conversations.each do |conversation| %>
      <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        <% unless current_user.id == recipient %>
          <div class="columns">
            <div class="column">
              
              <div class="inline-block"><%= link_to recipient.email,
              coversations_messages_path(conversation) %></div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoeseek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "View All", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% if user_signed_in? %>
          <li><%=link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
          <%else %>
          <li><%= link_to "Sign In",new_user_session_path %></li>
          <% end %>
        </ul>
         <ul class="nav nav-bar navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to "Add Shoes", new_shops_path%></li>
          <li> 

          </li>


   
 
          <ul class="nav nav-bar navbar-right">
          <li class="dropdown">
              <a href="" class="dropdown-toggle"data-toggle="dropdown" role="button" arias-expanded="false">Categories<span class="caret"></span></a>
             <ul class="" role="menu">
                 <% Category.all.each do |category| %>
                <li class="<%'active' if params[:category ] == category.name%>">
                  <%= link_to category.name, shops_path(category: category.name), class: "link"%>
               </li>
              <% end %>
            </ul>
          </li>
        </ul>
 


          <% end %>
           
         </ul>
      </div>
      
    </nav>


    <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1 class="title is-4">Message <%= @conversation.recipient.email %></h1>

<% if @over_ten %>
  <%= link_to "Show previous", '?m=all', class:'button is-link' %>
<% end %>

<section id="messages" class="mb4">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <article class="message is-dark">
        <div class="message-body">
          <div class="inline-block nudge-down-10 pr2"><%= gravatar_for user, size: 32 %></div>
          <div class="inline-block"><strong><%= user.email %></strong> <%= message.message_time %></div>
          <div class="block pt4">
            <div class="f4"><%= sanitize markdown_to_html(message.body) %></div>
          </div>
        </div>
      </article>
    <% end %>
  <% end %>
</section>

<%= form_for [@conversation, @message] do |f| %>
  <%= f.text_area :body, class: "textarea", placeholder: "Inquire about a trade..." %>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
  <div class="text-align-right">
    <%= f.submit "Send message", class: "button is-link is-large mt3" %>
  </div>
<% end %>

app/views/shops/_form.html.erb
<% if shop.errors.any? %>
    <div class="errors">
        <% shop.errors.full_messages.each do |error| %>
            <p><%= error %></p>
        <% end %>
    </div>
<% end %>


<%= simple_form_for @shop do |f| %>

<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select category") %>

<%= f.input :title, label: "Shoes title" %>
<%= f.input :description %>
<%= f.input :color %>
<%= f.input :price %>
<%= f.input :image  %>


<%= f.button :submit, value: "Create"%>
<% end %>

<!-- # <%= form_with model: shop, local: true do |form| %>

#  <div>
#  	 <%= form.label :title%>
#  	 <%= form.text_field :title, value: shop.title %>
#  </div>
#  <div>
#  	 <%= form.label :description %>
#  	 <%= form.text_area :description, value: shop.description%>
#  </div>
#  <div>
#  	 <%= form.label :price%>
#  	 <%= form.number_field :price, value: shop.price %>
#  </div>

#  <div>
#  	<%= form.submit value: "Create" %>
#  </div>
#  
# <%end%> -->

app/views/shops/edit.html.erb
<h1>Edit</h1>

<%= render 'form', shop: @shop %>

app/views/shops/index.html.erb
<h1 class="current-category"> <%= params[:category]%></h1>
<% if @shops.count == 0%>
  <h1>There are no books currently in this category</h1>
 <% else %>
      <% @shops.each do |shop|%>
 <div class="">
    <div class="col-md-3">
    	<div class="listing">
      <%= image_tag shop.image if shop.image.attached? %>
   

 <h2><%= link_to "#{shop.title} - #{shop.color}- #{number_to_currency(shop.price)}", shop_path(shop.id) %></h2>

  </div>
</div>
<%end%>
<%end%>

app/views/shops/new.html.erb
<%= render 'form', shop: @shop %>

app/views/shops/show.html.erb
 <div class="container">
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <ul class="list-unstyled mt-3 mb-4">
              <li><h1><%= @shop.title%></h1></li>
              <li><p><%= @shop.description%></p></li>
              <li><%= image_tag(@shop.image) if @shop.image.attached? %></li>
            </ul>
           <button data-stripe="payment" class= "btn btn-lg btn-block btn-primary">Check Out <%= number_to_currency(@shop.price) %></button>
       <% if user_signed_in? %>

       <% if @shop.user_id == current_user.id %>
          <h1><%=link_to "Edit", edit_shops_path(@shop)%></h1>
          <h1><%= link_to 'Delete', @shop, method: :delete, data: { confirm: 'Are you sure?' } %></h1>
        <%end%>
        <%end%>
      </div>
 </div>
 

  <% if user_signed_in? && current_user.id != @shop.user_id %>
      <%= link_to "Message #{@shop.user.email}", conversations_path(sender_id: current_user.id, recipient_id: @shop.user.id), method: 'post', class:"button is-link" %>
    <% elsif user_signed_in? && current_user.id == @shop.user_id  %>
      <%= link_to "Conversations", conversations_path(@Conversation) %>
    <% else %>

    <%= link_to "Sign up to message #{@trade.user.email}", new_user_registration_path %>
    <% end %>


<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>